# Generated by Django 5.1.2 on 2026-04-22 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
