# Generated by Django 5.1.2 on 2026-04-22 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
