# Generated by Django 5.1.2 on 2026-04-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_productioncompany_person_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
