# Generated by Django 6.0.4 on 2026-04-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_moviereview_created_at'),
        ('movies', '0009_moviereviewlike'),
        ('movies', '0013_moviereview_created_at'),
    ]

    operations = [
    ]
