# Generated by Django 5.1.2 on 2026-04-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_merge_20260423_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
