# Generated by Django 5.1.2 on 2026-04-24 11:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_alter_moviereview_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviereview',
            unique_together={('user', 'movie')},
        ),
    ]
